version: '3'

services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
#      - ./db:/docker-entrypoint-initdb.d/
      - django-treebeard-db-test:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
    django-treebeard-db-test:
      external: false